---
abstract: 'Compilable, nearly transparent SSL encapsulation for IO::Socket::INET.'
author:
  - 'cPanel Inc, Steffen Ullrich <sullr@cpan.org>, Peter Behroozi, Marko Asplund'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: cPanel-IO-Socket-SSL
no_index:
  directory:
    - t
    - inc
requires:
  Net::SSLeay: '1.46'
  Scalar::Util: '0'
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Queue=cPanel-IO-Socket-SSL
  homepage: https://github.com/rurban/cPanel-IO-Socket-SSL
  license: http://dev.perl.org/licenses/
  repository: https://github.com/rurban/cPanel-IO-Socket-SSL
version: 1.994_01
